/*
 * MainFrame.java
 *
 * Created on 23. März 2006, 23:55
 */

package downloader;

/*
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 3.1.0
 *
 */

// http://www.jjgirls.com/asian4you/sandra-mar/[80-82]/sandra-mar-[1-12].jpg
// http://www.jjgirls.com/asian4you/[1-5:3]/sandra-mar/[80-82]/sandra-mar-[1-12].jpg

import java.awt.event.MouseEvent;
import java.io.File;

public class MainFrame extends javax.swing.JFrame {

    public final static String NAME    = "MythGraphics Downloader";
    public final static String VERSION = "3.1.0";
    public final static int BUFFERSIZE = 0x200000; // 2 MB

    private final static String LOGFILESTRING = ".mythgraphics/Downloader/log.txt";

    private int thai = -1; // ThreadArrayIndex --> max index

    private final DownloadThread[] tha = new DownloadThread[0xFF];
    private final File logfile = new File(LOGFILESTRING);

    public MainFrame() {
        initComponents();
        scrollPane1.setAutoscrolls(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new javax.swing.JPopupMenu();
        menuItem1 = new javax.swing.JMenuItem();
        menuItem2 = new javax.swing.JMenuItem();
        source1 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        scrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        target1 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();

        menuItem1.setText("leeren");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem1ActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItem1);

        menuItem2.setText("speichern");
        menuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem2ActionPerformed(evt);
            }
        });
        popupMenu1.add(menuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(NAME + " v" + VERSION);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setText("Quell-Adresse (http://www.abc.de/path/file[Start-Ende:FixStellen].xyz):");

        button1.setText("Start");
        button1.setToolTipText("Neuen Download mit den angegebenen Daten starten");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        scrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        textArea1.setEditable(false);
        textArea1.setToolTipText("Links-Klick, um ganz nach unten zu scrollen; Rechts-Klick, um Menü anzuzeigen");
        textArea1.setComponentPopupMenu(popupMenu1);
        textArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textArea1MouseClicked(evt);
            }
        });
        scrollPane1.setViewportView(textArea1);

        label2.setText("Ziel-Adresse (Verzeichnis):");

        button2.setText("Stop / Abbrechen");
        button2.setToolTipText("Abbrechen der Downloads in FILO-Reihenfolge");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addComponent(source1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(target1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addGap(4, 4, 4)
                .addComponent(source1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(target1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 771, 503);
    }// </editor-fold>//GEN-END:initComponents

    private boolean write2Log() {
        return io.IO.mkFile(logfile) && io.IO.writeToFile( textArea1.getText(), logfile, false );
    }

    private void menuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem2ActionPerformed
        if ( write2Log() ) {
            printMessage("Log-Daten erfolgreich gespeichert");
        } else {
            printMessage("Fehler beim Schreiben der Log-Daten");
        }
    }//GEN-LAST:event_menuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try { Thread.sleep(1000); } catch (InterruptedException e) {}
        write2Log();
    }//GEN-LAST:event_formWindowClosing

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        for (int i = thai; i >= 0; --i) {
            if ( (tha[thai] != null) && tha[thai].isActiveState() ) {
                tha[thai].interrupt();
                printMessage("Download " + (thai+1) + " unterbrochen.");
            }
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void textArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textArea1MouseClicked
        if ( evt.getButton() == MouseEvent.BUTTON1 ) { scrollDown(); }
    }//GEN-LAST:event_textArea1MouseClicked

    private void scrollDown() {
        scrollPane1.getVerticalScrollBar().setValue(
            scrollPane1.getVerticalScrollBar().getMaximum()
        );
    }

    private void menuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem1ActionPerformed
        textArea1.setText("");
    }//GEN-LAST:event_menuItem1ActionPerformed

    int getActiveDownloads() {
        int c = 0;
        for (DownloadThread x : tha) {
            if ( (x != null) && x.isActiveState() ) { ++c; }
        }
        return c;
    }

    void handleException(Exception e) {
        StackTraceElement[] array = e.getStackTrace();
        printMessage( e.toString() );
        for (int i = 0; i < array.length; ++i)
            printMessage( "        " + array[i].toString() );
    }

    synchronized void printMessage(String s) {
        textArea1.append(s + "\n");
        scrollDown();
    }

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        ++thai;
        tha[thai] = new DownloadThread(this);
        tha[thai].start();
        printMessage("... gestartet");
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton button1;
    javax.swing.JButton button2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JMenuItem menuItem1;
    private javax.swing.JMenuItem menuItem2;
    private javax.swing.JPopupMenu popupMenu1;
    private javax.swing.JScrollPane scrollPane1;
    javax.swing.JTextField source1;
    javax.swing.JTextField target1;
    private javax.swing.JTextArea textArea1;
    // End of variables declaration//GEN-END:variables

}
